### PR TITLE
Bugfix: implemented signal to change the gain setting when the checkb…

### LINKED ISSUE #45: Checkbox "Peak Det Hi Gain" not working in Parameters Tab of GUI
**Describe the bug**
The Checkbox "Peak Det Hi Gain" is not working in the Tab Parameters of the GUI. Also there is no effect on the GPIO Pin of the RaspberryPi. 
The Checkbox "High Gain" in the tab "Overview" is working and has effect on the GPIO Pin of the RaspberryPi.

**To Reproduce**
Toggle the Checkbox in the Tab Parameters and measure the voltage of the HI_GAIN Pin. The voltage level does not change. Toggle the Checkbox "High Gain" in the tab "Overview". The voltage level changes between 0V and 3V3.

**Expected behavior**
Both Checkboxes should have the same behavior. Also the Checkbox should have the same labeling.

### PR DESCRIPTION
**Pull request by hangeza**
…ox in "Parameters" tab in the GUI is clicked

closes issue #45

### CODE REVIEW

File: source/gui/src/parametermonitorform.cpp [hunk 1]
```diff
@@ -44,6 +44,10 @@ ParameterMonitorForm::ParameterMonitorForm(QWidget *parent) :
         {
             emit biasEnableChanged(checked);
         } );
+    connect(ui->hiGainCheckBox, &QCheckBox::clicked, this, [this](bool checked)
+        {
+            emit gainSwitchChanged(checked);
+        } );
```
Comment (dtreffenstaedt) [inline source/gui/src/parametermonitorform.cpp]: Signals can be connected to other signals for automatic forwarding. No lambda necessary.
```suggestion
    connect(ui->hiGainCheckBox, &QCheckBox::clicked, this, &ParameterMointorForm::gainSwitchChanged);
```

**Review by dtreffenstaedt — CHANGES_REQUESTED** [review]

**Review by dtreffenstaedt — APPROVED** [review]
A quick test seems to confirm this works.
